# -*- coding: utf-8 -*-
"""experimental sle project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPAUzKYx3QZjQZnmyYs3fnLP6WlFGaDT
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold, SelectFromModel

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import roc_auc_score, accuracy_score, roc_curve
import matplotlib.pyplot as plt

pip install GEOparse

import GEOparse

# Download directly from GEO
gse = GEOparse.get_GEO(
    geo="GSE65391",
    destdir="data"
)

print(gse)

print("Number of samples:", len(gse.gsms))

# view one sample
sample_id = list(gse.gsms.keys())[0]
print(gse.gsms[sample_id].metadata)

import pandas as pd

expr_list = []

for gsm_name, gsm in gse.gsms.items():
    df = gsm.table[['ID_REF', 'VALUE']].copy()
    df.columns = ['gene', gsm_name]
    df = df.set_index('gene')
    expr_list.append(df)

# merge all samples
X = pd.concat(expr_list, axis=1).T

print("Expression shape:", X.shape)
X.head()

y = {}

for gsm_name, gsm in gse.gsms.items():
    meta = gsm.metadata.get("characteristics_ch1", [])
    text = " ".join(meta).lower()

    if "healthy" in text:
        y[gsm_name] = 0
    elif "sle" in text or "systemic lupus" in text:
        y[gsm_name] = 1
    else:
        y[gsm_name] = None

y = pd.Series(y)

# align with expression matrix
X = X.loc[y.dropna().index]
y = y.dropna()

print(y.value_counts())
print(X.shape)

import numpy as np

# numeric conversion
X = X.apply(pd.to_numeric, errors='coerce')

# fill missing values
X = X.fillna(X.mean())

print("Final dataset:", X.shape)

import pickle

with open("GSE65391_clean.pkl", "wb") as f:
    pickle.dump({"X": X, "y": y}, f)

print("Saved: GSE65391_clean.pkl")

with open("GSE65391_clean.pkl", "rb") as f:
    data = pickle.load(f)

X = data["X"]   # DataFrame with probe IDs as columns
y = data["y"]

print(X.shape)
print(y.value_counts())

import GEOparse
import pandas as pd
import numpy as np

gpl_train = GEOparse.get_GEO(geo="GPL10558", destdir="data")
platform_train = gpl_train.table

print(platform_train.columns)
platform_train.head()

probe_to_gene_train = platform_train.set_index("ID")["ILMN_Gene"]

X_gene = X.copy()
X_gene.columns = X_gene.columns.map(probe_to_gene_train)

# remove unmapped
X_gene = X_gene.loc[:, X_gene.columns.notna()]
X_gene = X_gene.loc[:, X_gene.columns != ""]

# average duplicate probes
X_gene = X_gene.T.groupby(level=0).mean().T

print("Gene-level data:", X_gene.shape)

def fix_excel_gene_names(gene):
    gene = str(gene)

    month_map = {
        "Jan": "JAN",
        "Feb": "FEB",
        "Mar": "MARCH",
        "Apr": "APR",
        "May": "MAY",
        "Jun": "JUN",
        "Jul": "JUL",
        "Aug": "AUG",
        "Sep": "SEPT",
        "Oct": "OCT",
        "Nov": "NOV",
        "Dec": "DEC"
    }

    if "-" in gene:
        parts = gene.split("-")
        if len(parts) == 2:
            num, month = parts
            if month in month_map:
                return month_map[month] + num

    return gene

X_gene_fixed = X_gene.copy()

X_gene_fixed.columns = [fix_excel_gene_names(col) for col in X_gene_fixed.columns]

# collapse again in case corrected names create duplicates
X_gene_fixed = X_gene_fixed.T.groupby(level=0).mean().T

print(X_gene_fixed.columns[:50])
print(X_gene_fixed.shape)

[col for col in X_gene_fixed.columns if "-" in str(col)][:20]

from google.colab import drive
drive.flush_and_unmount()

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

# Main project folder
project_path = "/content/drive/MyDrive/SLE_GEO_Project"

os.makedirs(
    project_path,
    exist_ok=True
)

print("Created:", project_path)

X_gene_fixed.to_pickle("/content/drive/MyDrive/SLE_GEO_Project/GSE65391_gene_level_FIXED.pkl")
X_gene_fixed.to_csv("/content/drive/MyDrive/SLE_GEO_Project/GSE65391_gene_level_FIXED.csv")

import os
print(os.listdir("/content/drive/MyDrive/SLE_GEO_Project"))

print("Total rows:", X_gene.shape[0])
print("Unique samples:", X_gene.index.nunique())

print(X_gene_fixed.columns[:50])

X_work = X_gene_fixed.copy()

X_work = X_gene_fixed.copy()

if X_work.min().min() >= 0:
    X_work = np.log1p(X_work)
    print("log1p applied")
else:
    print("log1p skipped")

from sklearn.model_selection import train_test_split

X_train_df, X_test_df, y_train, y_test = train_test_split(
    X_work,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

expr_mask = (X_train_df > 0).mean(axis=0) > 0.3

X_train_expr = X_train_df.loc[:, expr_mask]
X_test_expr = X_test_df.loc[:, expr_mask]

print("After expression filter:", X_train_expr.shape)

vt = VarianceThreshold(threshold=0.001)

X_train_vt = vt.fit_transform(X_train_expr)
X_test_vt = vt.transform(X_test_expr)

vt_genes = X_train_expr.columns[vt.get_support()]

X_train_vt_df = pd.DataFrame(X_train_vt, index=X_train_expr.index, columns=vt_genes)
X_test_vt_df = pd.DataFrame(X_test_vt, index=X_test_expr.index, columns=vt_genes)

print("After variance filter:", X_train_vt_df.shape)
print("Genes kept:", len(vt_genes))

# Top 10,000 variable genes
variances = X_train_vt_df.var(axis=0)

top10000_genes = variances.sort_values(ascending=False).head(10000).index

X_train_10000 = X_train_vt_df[top10000_genes]
X_test_10000 = X_test_vt_df[top10000_genes]

from sklearn.preprocessing import StandardScaler

scaler_10000 = StandardScaler()

X_train_10000_scaled = scaler_10000.fit_transform(X_train_10000)
X_test_10000_scaled = scaler_10000.transform(X_test_10000)

X_train_10000_scaled
X_test_10000_scaled
y_train
y_test

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=400,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="logloss"
    )
}

from sklearn.metrics import confusion_matrix, classification_report

results = []

trained_models = {}

for name, model in models.items():
    print("Training:", name)

    model.fit(X_train_10000_scaled, y_train)

    y_pred = model.predict(X_test_10000_scaled)
    y_prob = model.predict_proba(X_test_10000_scaled)[:, 1]

    auc = roc_auc_score(y_test, y_prob)
    acc = accuracy_score(y_test, y_pred)

    trained_models[name] = model

    results.append({
        "Model": name,
        "Accuracy": acc,
        "ROC_AUC": auc
    })

    print("AUC:", auc)
    print("Accuracy:", acc)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print("-" * 50)

model_results = pd.DataFrame(results).sort_values("ROC_AUC", ascending=False)

model_results

# ==========================================================
# ADD-ON CODE: Threshold tuning to reduce misclassification
# ==========================================================

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_auc_score, roc_curve
import numpy as np
import pandas as pd

for name, model in trained_models.items():
    print("\n" + "="*70)
    print("MODEL:", name)
    print("="*70)

    y_prob = model.predict_proba(X_test_10000_scaled)[:, 1]

    # ROC-based best threshold
    fpr, tpr, thresholds = roc_curve(y_test, y_prob)
    best_idx = np.argmax(tpr - fpr)
    best_threshold = thresholds[best_idx]

    print("Best ROC threshold:", best_threshold)

    y_pred_tuned = (y_prob >= best_threshold).astype(int)

    print("\nAfter ROC threshold tuning:")
    print("Accuracy:", accuracy_score(y_test, y_pred_tuned))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))
    print(confusion_matrix(y_test, y_pred_tuned))
    print(classification_report(y_test, y_pred_tuned))

    # Manual thresholds to reduce Healthy -> SLE false positives
    print("\nManual threshold comparison:")

    threshold_results = []

    for threshold in [0.5, 0.6, 0.7, 0.8, 0.9]:
        y_pred_temp = (y_prob >= threshold).astype(int)

        cm = confusion_matrix(y_test, y_pred_temp)
        tn, fp, fn, tp = cm.ravel()

        acc = accuracy_score(y_test, y_pred_temp)
        auc = roc_auc_score(y_test, y_prob)
        sensitivity = tp / (tp + fn)
        specificity = tn / (tn + fp)

        threshold_results.append({
            "Model": name,
            "Threshold": threshold,
            "Accuracy": acc,
            "ROC_AUC": auc,
            "Sensitivity_SLE": sensitivity,
            "Specificity_Healthy": specificity,
            "False_Positive_Healthy_as_SLE": fp,
            "False_Negative_SLE_as_Healthy": fn
        })

    threshold_results_df = pd.DataFrame(threshold_results)
    display(threshold_results_df)

# FINAL tuned prediction (use this for future)
threshold = 0.9

y_pred_final = (y_prob >= threshold).astype(int)

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))
plt.bar(model_results["Model"], model_results["ROC_AUC"])
plt.xlabel("Model")
plt.ylabel("ROC-AUC")
plt.title("Model Comparison Based on ROC-AUC")
plt.ylim(0, 1)
plt.xticks(rotation=20)
plt.show()

plt.figure(figsize=(7,5))
plt.bar(model_results["Model"], model_results["Accuracy"])
plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.title("Model Comparison Based on Accuracy")
plt.ylim(0, 1)
plt.xticks(rotation=20)
plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

plt.figure(figsize=(7,6))

for name, model in trained_models.items():
    y_prob = model.predict_proba(X_test_10000_scaled)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f"{name} AUC = {roc_auc:.3f}")

plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

import os

save_path = "/content/drive/MyDrive/SLE_GEO_Project/MANUSCRIPT_FIGURES"
os.makedirs(save_path, exist_ok=True)

plt.savefig(
    os.path.join(save_path, "Figure_2.tiff"),  # journals prefer TIFF
    dpi=600,                  # high resolution
    bbox_inches="tight",
    format="tiff"
)

import os

print(os.listdir("/content/drive/MyDrive/SLE_GEO_Project/MANUSCRIPT_FIGURES"))

model_results.to_csv("model_comparison_results.csv", index=False)
print("Saved model_comparison_results.csv")

# Select best model based on highest ROC-AUC
best_model_name = model_results.sort_values("ROC_AUC", ascending=False).iloc[0]["Model"]

final_model = trained_models[best_model_name]

print("Best model selected:", best_model_name)
print("Best ROC-AUC:", model_results.loc[model_results["Model"] == best_model_name, "ROC_AUC"].values[0])

# Get probabilities from final selected model
y_prob = final_model.predict_proba(X_test_10000_scaled)[:, 1]

# Final chosen threshold
threshold = 0.9

# Final tuned predictions
y_pred_final = (y_prob >= threshold).astype(int)

# Evaluate final tuned model
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_auc_score

print("Final Accuracy:", accuracy_score(y_test, y_pred_final))
print("Final ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nFinal Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_final))

print("\nFinal Classification Report:")
print(classification_report(y_test, y_pred_final))

import joblib

# Save final selected model
joblib.dump(final_model, "final_best_model.pkl")

# Save model name
joblib.dump(best_model_name, "final_best_model_name.pkl")

# Save final threshold
joblib.dump(threshold, "final_threshold.pkl")

# Save performance values
final_results = {
    "Accuracy": accuracy_score(y_test, y_pred_final),
    "ROC_AUC": roc_auc_score(y_test, y_prob),
    "Threshold": threshold,
    "Confusion_Matrix": confusion_matrix(y_test, y_pred_final),
    "Classification_Report": classification_report(y_test, y_pred_final, output_dict=True)
}

joblib.dump(final_results, "final_model_results.pkl")

print("Final model saved successfully:")
print("final_best_model.pkl")
print("final_best_model_name.pkl")
print("final_threshold.pkl")
print("final_model_results.pkl")

joblib.dump(scaler_10000, "scaler_10000.pkl")
joblib.dump(list(top10000_genes), "top10000_genes.pkl")

print("Saved scaler_10000.pkl and top10000_genes.pkl")

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd
import numpy as np

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scoring = {
    "accuracy": "accuracy",
    "roc_auc": "roc_auc",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1"
}

from sklearn.pipeline import Pipeline

cv_results = []

for name, model in models.items():
    print("Cross-validating:", name)

    scores = cross_validate(
        Pipeline([
            ("scaler", StandardScaler()),
            ("model", model)
        ]),
        X_train_10000,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1,
        return_train_score=False
    )

    cv_results.append({
        "Model": name,
        "Accuracy_mean": scores["test_accuracy"].mean(),
        "Accuracy_std": scores["test_accuracy"].std(),
        "ROC_AUC_mean": scores["test_roc_auc"].mean(),
        "ROC_AUC_std": scores["test_roc_auc"].std(),
        "Precision_mean": scores["test_precision"].mean(),
        "Recall_mean": scores["test_recall"].mean(),
        "F1_mean": scores["test_f1"].mean()
    })

cv_results_df = pd.DataFrame(cv_results).sort_values("ROC_AUC_mean", ascending=False)

cv_results_df

best_cv_model_name = cv_results_df.iloc[0]["Model"]
print("Best CV model:", best_cv_model_name)

final_model = models[best_cv_model_name]
final_model.fit(X_train_10000_scaled, y_train)

print("Final model trained:", best_cv_model_name)

best_cv_model_name = cv_results_df.iloc[0]["Model"]
print("Best CV model:", best_cv_model_name)

final_model = models[best_cv_model_name]

final_model.fit(X_train_10000, y_train)

print("Final model trained:", best_cv_model_name)

import joblib

joblib.dump(final_model, "final_best_cv_model.pkl")
joblib.dump(best_cv_model_name, "final_best_cv_model_name.pkl")
joblib.dump(list(top10000_genes), "top10000_genes.pkl")

print("Saved final CV model and top10000 genes")

from sklearn.pipeline import Pipeline
import joblib

best_cv_model_name = cv_results_df.iloc[0]["Model"]
print("Best CV model:", best_cv_model_name)

final_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", models[best_cv_model_name])
])

final_model.fit(X_train_10000, y_train)

print("Final model trained:", best_cv_model_name)

joblib.dump(final_model, "final_best_cv_model.pkl")
joblib.dump(best_cv_model_name, "final_best_cv_model_name.pkl")
joblib.dump(list(top10000_genes), "top10000_genes.pkl")

print("Saved final CV pipeline model and top10000 genes")

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train_10000_scaled, y_train)

import shap
import numpy as np
import pandas as pd

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test_10000_scaled)

shap.summary_plot(shap_values, X_test_10000_scaled)

# convert test data back to dataframe
X_test_df = pd.DataFrame(X_test_10000_scaled, columns=top10000_genes)

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test_df)

shap.summary_plot(shap_values, X_test_df)

plt.savefig("/content/drive/MyDrive/SLE_GEO_Project/MANUSCRIPT_FIGURES/Figure_5_SHAP_Summary.tiff",
            dpi=600, bbox_inches="tight", format="tiff")

shap_importance = np.abs(shap_values).mean(axis=0)

shap_df = pd.DataFrame({
    "Gene": top10000_genes,
    "Importance": shap_importance
}).sort_values("Importance", ascending=False)

top8_genes = shap_df.head(8)["Gene"].tolist()

print("Top 8 genes:", top8_genes)

shap_importance = shap_importance / shap_importance.sum()

# remove unknown / poorly annotated genes
filtered_genes = [g for g in top8_genes if not (
    g.startswith("LOC") or
    g.startswith("HS.") or
    "orf" in g.lower()
)]

print("Filtered genes:", filtered_genes)

# get next ranked genes from SHAP
additional_genes = shap_df[
    ~shap_df["Gene"].isin(filtered_genes)
]

# remove unknown ones
additional_genes = additional_genes[
    ~additional_genes["Gene"].str.startswith(("LOC", "HS."))
]

# take top needed
needed = 8 - len(filtered_genes)

extra = additional_genes.head(needed)["Gene"].tolist()

final_genes = filtered_genes + extra

print("Final 8 genes:", final_genes)

final_genes = ['IFI27', 'ZBP1', 'SCRN1', 'ABCB1', 'CDCA7', 'GADD45A', 'TFDP1', 'KLHDC8B']

[x for x in globals() if 'shap' in x.lower()]

shap_df.columns

shap_df[shap_df["Gene"].isin(["IFI27", "CDCA7", "ZBP1"])]

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import joblib

X_train_clean = X_train_vt_df[final_genes]
X_test_clean = X_test_vt_df[final_genes]

clean_scaler = StandardScaler()

X_train_clean_scaled = clean_scaler.fit_transform(X_train_clean)
X_test_clean_scaled = clean_scaler.transform(X_test_clean)

clean_model = LogisticRegression(
    max_iter=5000,
    class_weight="balanced",
    random_state=42
)

clean_model.fit(X_train_clean_scaled, y_train)

from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

y_pred_clean = clean_model.predict(X_test_clean_scaled)
y_prob_clean = clean_model.predict_proba(X_test_clean_scaled)[:, 1]

print("Clean 8-gene Accuracy:", accuracy_score(y_test, y_pred_clean))
print("Clean 8-gene AUC:", roc_auc_score(y_test, y_prob_clean))
print(classification_report(y_test, y_pred_clean))

# Commented out IPython magic to ensure Python compatibility.
# %whos

for var in [
    "acc_clean",
    "auc_clean",
    "cm_clean",
    "report_clean"
]:
    print(var, var in globals())

import joblib

# Save clean model
joblib.dump(clean_model, "diagnosis_model_clean8.pkl")

# Save scaler
joblib.dump(clean_scaler, "scaler_clean8.pkl")

# Save final genes
joblib.dump(final_genes, "final_clean_8_genes.pkl")


print("Saved successfully")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_clean)

print("Confusion Matrix:")
print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Healthy", "SLE"]
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix - Final 8 Gene Model")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import roc_curve, auc, confusion_matrix, ConfusionMatrixDisplay

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, y_prob_clean)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0, 1], [0, 1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - 8 Gene Model")
plt.legend()

plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Use FINAL tuned predictions
cm = confusion_matrix(y_test, y_pred_clean)

print("Confusion Matrix:")
print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Healthy", "SLE"]
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix - Final Tuned 8 Gene Model")
plt.grid(False)   # cleaner plot (optional but recommended)

plt.show()

import pandas as pd

risk_plot_df = pd.DataFrame({
    "Risk_Probability": y_prob_clean,
    "True_Label": y_test
})

print(risk_plot_df.head())

risk_plot_df["True_Label_Name"] = risk_plot_df["True_Label"].map({
    0: "Healthy",
    1: "SLE"
})

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

sns.histplot(
    data=risk_plot_df,
    x="Risk_Probability",
    hue="True_Label_Name",
    bins=30,
    kde=True
)

plt.title("Risk Score Distribution - 8 Gene Model")
plt.xlabel("Predicted Probability (SLE Risk)")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(6,5))

sns.boxplot(
    data=risk_plot_df,
    x="True_Label_Name",
    y="Risk_Probability"
)

plt.title("Risk Score Comparison")
plt.xlabel("Class")
plt.ylabel("Predicted SLE Probability")

plt.show()

final_threshold_8gene = 0.7

risk_plot_df["Pred_Label"] = (risk_plot_df["Risk_Probability"] >= final_threshold_8gene).astype(int)

risk_plot_df["Pred_Label_Name"] = risk_plot_df["Pred_Label"].map({
    0: "Healthy",
    1: "SLE"
})

misclassified = risk_plot_df[
    risk_plot_df["True_Label"] != risk_plot_df["Pred_Label"]
]

print("Misclassified samples:")
print(misclassified.head())

# Check probability distribution of misclassified vs correct
import seaborn as sns
import matplotlib.pyplot as plt

risk_plot_df["Correct"] = risk_plot_df["True_Label"] == risk_plot_df["Pred_Label"]

plt.figure(figsize=(7,5))

sns.boxplot(
    data=risk_plot_df,
    x="Correct",
    y="Risk_Probability"
)

plt.title("Risk Score: Correct vs Misclassified")
plt.show()

top8_shap_df = shap_df[shap_df["Gene"].isin(final_genes)].copy()
top8_shap_df = top8_shap_df.sort_values("Importance", ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(
    data=top8_shap_df,
    x="Importance",
    y="Gene"
)

plt.xlabel("Mean Absolute SHAP Importance")
plt.ylabel("Gene")
plt.title("Final 8-Gene Biomarker Importance")

plt.show()

top8_genes  = shap_df.head(8)["Gene"].tolist()
top10_genes = shap_df.head(10)["Gene"].tolist()
top15_genes = shap_df.head(15)["Gene"].tolist()

print("Top 8:", top8_genes)
print("Top 10:", top10_genes)
print("Top 15:", top15_genes)

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score

def evaluate_model(gene_list, X_train_df, X_test_df, y_train, y_test):

    X_train = X_train_df[gene_list]
    X_test = X_test_df[gene_list]

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    model = LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        random_state=42
    )

    model.fit(X_train, y_train)

    prob = model.predict_proba(X_test)[:, 1]
    pred = model.predict(X_test)

    return {
        "AUC": roc_auc_score(y_test, prob),
        "Accuracy": accuracy_score(y_test, pred),
        "F1": f1_score(y_test, pred)
    }

import pandas as pd

results = []

results.append({
    "Model": "Top 8 Genes",
    **evaluate_model(top8_genes, X_train_vt_df, X_test_vt_df, y_train, y_test)
})

results.append({
    "Model": "Top 10 Genes",
    **evaluate_model(top10_genes, X_train_vt_df, X_test_vt_df, y_train, y_test)
})

results.append({
    "Model": "Top 15 Genes",
    **evaluate_model(top15_genes, X_train_vt_df, X_test_vt_df, y_train, y_test)
})

results_df = pd.DataFrame(results)

results_df

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

plt.plot(results_df["Model"], results_df["AUC"], marker="o", label="AUC")
plt.plot(results_df["Model"], results_df["Accuracy"], marker="o", label="Accuracy")
plt.plot(results_df["Model"], results_df["F1"], marker="o", label="F1")

plt.ylabel("Score")
plt.title("Gene Count vs Model Performance")
plt.ylim(0, 1)
plt.legend()
plt.show()

final_genes = ['IFI27', 'ZBP1', 'SCRN1', 'ABCB1', 'CDCA7', 'GADD45A', 'TFDP1', 'KLHDC8B']

X_train_final = X_train_vt_df[final_genes]
X_test_final = X_test_vt_df[final_genes]

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

final_scaler = StandardScaler()

X_train_final_scaled = final_scaler.fit_transform(X_train_final)
X_test_final_scaled = final_scaler.transform(X_test_final)

final_risk_model = LogisticRegression(
    max_iter=5000,
    class_weight="balanced",
    random_state=42
)

final_risk_model.fit(X_train_final_scaled, y_train)

from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

y_pred_final = final_risk_model.predict(X_test_final_scaled)
y_prob_final = final_risk_model.predict_proba(X_test_final_scaled)[:, 1]

print("Final Clean 8-Gene Accuracy:", accuracy_score(y_test, y_pred_final))
print("Final Clean 8-Gene AUC:", roc_auc_score(y_test, y_prob_final))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_final))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_final))

final_threshold_8gene = 0.7

y_pred_final_tuned = (y_prob_final >= final_threshold_8gene).astype(int)

print("Tuned Final 8-Gene Accuracy:", accuracy_score(y_test, y_pred_final_tuned))
print("Tuned Final 8-Gene AUC:", roc_auc_score(y_test, y_prob_final))

print("\nTuned Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_final_tuned))

print("\nTuned Classification Report:")
print(classification_report(y_test, y_pred_final_tuned))

import joblib

# Best version = UNTUNED (default threshold)
final_threshold = 0.5

# Save model
joblib.dump(final_risk_model, "best_8gene_model.pkl")

# Save scaler (IMPORTANT)
joblib.dump(final_scaler, "best_8gene_scaler.pkl")

# Save gene list
joblib.dump(final_genes, "best_8gene_genes.pkl")

# Save threshold
joblib.dump(final_threshold, "best_8gene_threshold.pkl")

print("Saved BEST 8-gene model (untuned), scaler, genes, and threshold")

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np

# Prepare data (8 genes)
X = X_train_vt_df[final_genes]
y = y_train

# Model
model = LogisticRegression(
    max_iter=5000,
    class_weight="balanced",
    random_state=42
)

# Pipeline (scaling inside CV)
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", model)
])

# Stratified 5-fold CV
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# AUC scores
cv_auc = cross_val_score(
    pipe,
    X,
    y,
    cv=cv,
    scoring='roc_auc'
)

# Accuracy scores
cv_acc = cross_val_score(
    pipe,
    X,
    y,
    cv=cv,
    scoring='accuracy'
)

print("CV AUC scores:", cv_auc)
print("Mean CV AUC:", np.mean(cv_auc))

print("\nCV Accuracy scores:", cv_acc)
print("Mean CV Accuracy:", np.mean(cv_acc))

import os
import joblib

base_path = "/content/drive/MyDrive/SLE_Project"
os.makedirs(base_path, exist_ok=True)

# Final threshold (use 0.5 for best version OR 0.7 if tuned)
final_threshold = 0.5

joblib.dump(final_risk_model, base_path + "/diagnosis_model_clean8.pkl")
joblib.dump(final_scaler, base_path + "/scaler_clean8.pkl")
joblib.dump(final_genes, base_path + "/final_clean_8_genes.pkl")
joblib.dump(final_threshold, base_path + "/threshold_clean8.pkl")

print("Clean final 8-gene model, scaler, genes, and threshold saved.")

from sklearn.calibration import calibration_curve
from sklearn.metrics import brier_score_loss
import matplotlib.pyplot as plt

# IMPORTANT: use unscaled data because final_model is a Pipeline
y_prob = final_model.predict_proba(X_test_10000)[:, 1]

# Calibration curve
prob_true, prob_pred = calibration_curve(
    y_test,
    y_prob,
    n_bins=10,
    strategy="uniform"
)

# Brier score
brier = brier_score_loss(y_test, y_prob)

print("Brier Score:", brier)

plt.figure(figsize=(6,6))
plt.plot(prob_pred, prob_true, marker="o", label="Final Diagnostic Model")
plt.plot([0,1], [0,1], linestyle="--", label="Perfect Calibration")

plt.xlabel("Mean Predicted Probability")
plt.ylabel("Observed Fraction of Positives")
plt.title(f"Calibration Curve\nBrier Score = {brier:.4f}")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

from sklearn.calibration import calibration_curve
from sklearn.metrics import brier_score_loss
import matplotlib.pyplot as plt

y_prob = final_model.predict_proba(X_test_10000)[:,1]

prob_true, prob_pred = calibration_curve(
    y_test,
    y_prob,
    n_bins=5,          # reduced bins
    strategy="quantile" # better for imbalance
)

brier = brier_score_loss(y_test, y_prob)

print("Brier Score:", brier)

plt.figure(figsize=(6,6))

plt.plot(
    prob_pred,
    prob_true,
    marker='o',
    linewidth=2,
    label='Final Diagnostic Model'
)

plt.plot(
    [0,1],
    [0,1],
    '--',
    linewidth=2,
    label='Perfect Calibration'
)

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title(
    f"Calibration Curve\nBrier Score = {brier:.4f}"
)

plt.legend()
plt.grid(alpha=0.3)

plt.savefig(
    f"{save_path}/Figure_Calibration_Final.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# Save calibration figure
save_path = "/content/drive/MyDrive/SLE_GEO_Project/MANUSCRIPT_FIGURES"

plt.figure(figsize=(6,6))

plt.plot(
    prob_pred,
    prob_true,
    marker='o',
    linewidth=2,
    label='Final Diagnostic Model'
)

plt.plot(
    [0,1],
    [0,1],
    '--',
    linewidth=2,
    label='Perfect Calibration'
)

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")

plt.title(
    f"Calibration Curve\nBrier Score = {brier:.4f}"
)

plt.legend()
plt.grid(alpha=0.3)

plt.savefig(
    f"{save_path}/Figure_Calibration_Final_Diagnostic_Model.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Calibration figure saved")

import os

base_path = "/content/drive/MyDrive/SLE_Project"

os.makedirs(base_path, exist_ok=True)

print("Folder created:", base_path)

os.listdir(base_path)

import joblib

base_path = "/content/drive/MyDrive/SLE_Project"

model = joblib.load(base_path + "/diagnosis_model_clean8.pkl")
scaler = joblib.load(base_path + "/scaler_clean8.pkl")
genes = joblib.load(base_path + "/final_clean_8_genes.pkl")
threshold = joblib.load(base_path + "/threshold_clean8.pkl")

print("Model genes:", genes)
print("Threshold:", threshold)

import pickle

project_objects = {
    "model": final_model,
    "scaler": scaler,
    "genes": final_genes,
    "y_test": y_test,
    "y_prob": y_prob,
    "y_pred": y_pred_final
}

with open("PROJECT_OBJECTS.pkl","wb") as f:
    pickle.dump(project_objects,f)

print(final_genes)

print(X_gene_fixed.shape)
print(y.shape)

print(len(y))

try:
    print(len(y_train))
except:
    pass

try:
    print(len(y_test))
except:
    pass

for var in list(globals().keys()):
    try:
        obj = globals()[var]

        if hasattr(obj, "shape"):
            print(var, obj.shape)

    except:
        pass

print(top8_shap_df)

important_genes = [
    "IFI27",
    "ZBP1",
    "SCRN1",
    "CDCA7"
]

import shap
import matplotlib.pyplot as plt

for gene in important_genes:

    shap.dependence_plot(
        gene,
        shap_values,
        X_test_df,
        show=False
    )

    plt.savefig(
        f"{gene}_dependence.png",
        dpi=600,
        bbox_inches="tight"
    )

    plt.show()

published_genes = [
    'IFI27',
    'IFIT1',
    'IFIT3',
    'MX1',
    'OAS1',
    'ISG15',
    'STAT1',
    'LY6E'
]

available_genes = [
    g for g in published_genes
    if g in X_gene_fixed.columns
]

print("Available genes:", available_genes)

published_genes = [
    'IFI27',
    'IFIT1',
    'IFIT3',
    'MX1',
    'OAS1',
    'ISG15',
    'STAT1',
    'LY6E'
]

available_genes_final = [
    g for g in published_genes
    if (g in X_train_df.columns) and (g in X_test_df.columns)
]

print(available_genes_final)

X_train_pub = X_train_df[available_genes_final]
X_test_pub = X_test_df[available_genes_final]

print(len(available_genes_final))

from sklearn.preprocessing import StandardScaler

scaler_pub = StandardScaler()

X_train_pub_scaled = scaler_pub.fit_transform(X_train_pub)
X_test_pub_scaled = scaler_pub.transform(X_test_pub)

from sklearn.linear_model import LogisticRegression

pub_model = LogisticRegression(
    max_iter=5000,
    random_state=42
)

pub_model.fit(
    X_train_pub_scaled,
    y_train
)

from sklearn.metrics import roc_auc_score, accuracy_score

pub_prob = pub_model.predict_proba(
    X_test_pub_scaled
)[:,1]

pub_pred = (pub_prob >= 0.5).astype(int)

pub_auc = roc_auc_score(y_test, pub_prob)
pub_acc = accuracy_score(y_test, pub_pred)

print("Published Signature AUC:", pub_auc)
print("Published Signature Accuracy:", pub_acc)

our_auc = roc_auc_score(y_test, y_prob_final)

print("Our 8-Gene AUC:", our_auc)

comparison_df = pd.DataFrame({
    "Signature":[
        "Published IFN Signature",
        "Proposed 8-Gene Signature"
    ],
    "AUC":[
        0.880568356374808,
        0.9831029185867896
    ]
})

print(comparison_df)

comparison_df.to_csv(
    "Biomarker_Signature_Comparison.csv",
    index=False
)

[x for x in globals().keys() if 'pub' in x.lower()]

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# ROC for published signature
fpr_pub, tpr_pub, _ = roc_curve(y_test, pub_prob)
pub_auc = auc(fpr_pub, tpr_pub)

# ROC for proposed 8-gene signature
fpr_8g, tpr_8g, _ = roc_curve(y_test, y_prob)
auc_8g = auc(fpr_8g, tpr_8g)

plt.figure(figsize=(6,5))

plt.plot(
    fpr_pub,
    tpr_pub,
    linewidth=2,
    label=f'Published IFN Signature (AUC = {pub_auc:.3f})'
)

plt.plot(
    fpr_8g,
    tpr_8g,
    linewidth=2,
    label=f'Proposed 8-Gene Signature (AUC = {auc_8g:.3f})'
)

plt.plot([0,1], [0,1], '--', linewidth=1)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Comparative ROC Analysis')
plt.legend(loc='lower right')

plt.tight_layout()
plt.show()

import GEOparse

gse_ext = GEOparse.get_GEO(
    geo="GSE61635",
    destdir="/content/data"
)

import pandas as pd

expr_list = []

for gsm_name, gsm in gse_ext.gsms.items():
    df = gsm.table[['ID_REF', 'VALUE']].copy()
    df.columns = ['gene', gsm_name]
    df = df.set_index('gene')
    expr_list.append(df)

X_ext = pd.concat(expr_list, axis=1).T

print("External shape:", X_ext.shape)

print(gse_ext.gpls.keys())

gpl = gse_ext.gpls["GPL570"]
annot = gpl.table

print(annot.columns)
annot.head()

annot = gpl.table[['ID', 'Gene Symbol']].copy()
annot.columns = ['probe', 'gene']

annot['gene'] = annot['gene'].str.split(' /// ').str[0]

probe_to_gene = annot.set_index('probe')['gene']

X_ext_gene = X_ext.copy()
X_ext_gene.columns = X_ext_gene.columns.map(probe_to_gene)

X_ext_gene = X_ext_gene.loc[:, X_ext_gene.columns.notna()]
X_ext_gene = X_ext_gene.loc[:, X_ext_gene.columns != ""]

X_ext_gene = X_ext_gene.T.groupby(level=0).mean().T

print("After mapping:", X_ext_gene.shape)

common_genes = [g for g in genes if g in X_ext_gene.columns]
missing_genes = [g for g in genes if g not in X_ext_gene.columns]

print("Available genes:", len(common_genes), "/", len(genes))
print("Missing genes:", missing_genes)

import joblib
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

import os
print(os.listdir(base_path))

import joblib

base_path = "/content/drive/MyDrive/SLE_Project"

model = joblib.load(base_path + "/diagnosis_model_clean8.pkl")
scaler = joblib.load(base_path + "/scaler_clean8.pkl")
genes = joblib.load(base_path + "/final_clean_8_genes.pkl")
threshold = joblib.load(base_path + "/threshold_clean8.pkl")

print("Genes:", genes)
print("Threshold:", threshold)

X_ext_final = X_ext_gene.reindex(columns=genes)

print("Shape:", X_ext_final.shape)
print("Missing values per gene:")
print(X_ext_final.isna().sum())

model = joblib.load(base_path + "/diagnosis_model_clean8.pkl")
scaler = joblib.load(base_path + "/scaler_clean8.pkl")
genes = joblib.load(base_path + "/final_clean_8_genes.pkl")

# Align genes
X_ext_final = X_ext_gene.reindex(columns=genes)

print("Shape:", X_ext_final.shape)
print("Missing values:\n", X_ext_final.isna().sum())

# Handle missing values
X_ext_final = X_ext_final.fillna(X_ext_final.mean())

# Scale
X_ext_final_scaled = scaler.transform(X_ext_final)

# Predict
threshold = joblib.load(base_path + "/threshold_clean8.pkl")

y_ext_prob = model.predict_proba(X_ext_final_scaled)[:, 1]
y_ext_pred = (y_ext_prob >= threshold).astype(int)

print("Predictions:", y_ext_pred[:10])

X_ext_final = X_ext_gene.reindex(columns=genes)

print(X_ext_final.shape)
print(X_ext_final.isna().sum())

import pandas as pd
import numpy as np

print("Prediction counts:")
print(pd.Series(y_ext_pred).value_counts())

print("\nPrediction percentages:")
print(pd.Series(y_ext_pred).value_counts(normalize=True) * 100)

print("\nProbability summary:")
print(pd.Series(y_ext_prob).describe())

X_ext_scaled = scaler.transform(X_ext_final)

y_pred_ext = model.predict(X_ext_scaled)
y_prob_ext = model.predict_proba(X_ext_scaled)[:, 1]

print("Training data range:")
print(X_train_final.describe())

print("\nExternal data range:")
print(X_ext_final.describe())

import numpy as np

if X_ext_final.min().min() >= 0:
    X_ext_final = np.log1p(X_ext_final)

# Step 1: align genes
X_ext_final = X_ext_gene.reindex(columns=genes)

# Step 2: log transform (IMPORTANT FIX)
if X_ext_final.min().min() >= 0:
    X_ext_final = np.log1p(X_ext_final)

# Step 3: fill missing values
X_ext_final = X_ext_final.fillna(X_ext_final.mean())

# Step 4: scale
X_ext_final_scaled = scaler.transform(X_ext_final)

# Step 5: predict
threshold = joblib.load(base_path + "/threshold_clean8.pkl")

y_ext_prob = model.predict_proba(X_ext_final_scaled)[:, 1]
y_ext_pred = (y_ext_prob >= threshold).astype(int)

# Step 6: check distribution
import pandas as pd
print(pd.Series(y_ext_prob).describe())

y_ext = {}

for gsm_name, gsm in gse_ext.gsms.items():
    meta = " ".join(gsm.metadata.get("characteristics_ch1", [])).lower()
    title = " ".join(gsm.metadata.get("title", [])).lower()
    source = " ".join(gsm.metadata.get("source_name_ch1", [])).lower()

    text = meta + " " + title + " " + source

    if "healthy" in text or "control" in text:
        y_ext[gsm_name] = 0
    elif "sle" in text or "lupus" in text:
        y_ext[gsm_name] = 1

y_ext = pd.Series(y_ext)

print(y_ext.value_counts())

import joblib

base_path = "/content/drive/MyDrive/SLE_Project"

model = joblib.load(base_path + "/diagnosis_model_clean8.pkl")
scaler = joblib.load(base_path + "/scaler_clean8.pkl")
genes = joblib.load(base_path + "/final_clean_8_genes.pkl")
threshold = joblib.load(base_path + "/threshold_clean8.pkl")

print("Genes:", genes)
print("Threshold:", threshold)

X_ext_final = X_ext_gene.reindex(columns=genes)

print("External shape:", X_ext_final.shape)
print("Missing values:")
print(X_ext_final.isna().sum())

import numpy as np

# log transform external data to match training scale
if X_ext_final.min().min() >= 0:
    X_ext_final = np.log1p(X_ext_final)

# fill missing values, if any
X_ext_final = X_ext_final.fillna(X_ext_final.mean())

print(X_ext_final.describe())

common_samples = X_ext_final.index.intersection(y_ext.index)

X_ext_final = X_ext_final.loc[common_samples]
y_ext_aligned = y_ext.loc[common_samples]

print("Aligned X:", X_ext_final.shape)
print("Aligned y:")
print(y_ext_aligned.value_counts())

X_ext_scaled = scaler.transform(X_ext_final)

y_prob_ext = model.predict_proba(X_ext_scaled)[:, 1]
y_pred_ext = (y_prob_ext >= threshold).astype(int)

print("Prediction counts:")
print(pd.Series(y_pred_ext).value_counts())

print("\nProbability summary:")
print(pd.Series(y_prob_ext).describe())

from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

print("External Accuracy:", accuracy_score(y_ext_aligned, y_pred_ext))
print("External AUC:", roc_auc_score(y_ext_aligned, y_prob_ext))

print("\nConfusion Matrix:")
print(confusion_matrix(y_ext_aligned, y_pred_ext))

print("\nClassification Report:")
print(classification_report(y_ext_aligned, y_pred_ext))

# Try multiple thresholds
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

threshold_results_ext = []

for t in [0.3, 0.4, 0.45, 0.5]:
    y_pred_temp = (y_prob_ext >= t).astype(int)

    cm = confusion_matrix(y_ext_aligned, y_pred_temp)
    tn, fp, fn, tp = cm.ravel()

    threshold_results_ext.append({
        "Threshold": t,
        "Accuracy": accuracy_score(y_ext_aligned, y_pred_temp),
        "Sensitivity_SLE": tp/(tp+fn),
        "Specificity_Healthy": tn/(tn+fp),
        "False_Positive": fp,
        "False_Negative": fn
    })

threshold_results_ext_df = pd.DataFrame(threshold_results_ext)
threshold_results_ext_df

old_threshold = 0.5
new_threshold = 0.3

from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix
import pandas as pd

y_pred_old = (y_prob_ext >= old_threshold).astype(int)

cm_old = confusion_matrix(y_ext_aligned, y_pred_old)
tn_old, fp_old, fn_old, tp_old = cm_old.ravel()

old_results = {
    "Model": "Old Threshold",
    "Threshold": old_threshold,
    "Accuracy": accuracy_score(y_ext_aligned, y_pred_old),
    "ROC_AUC": roc_auc_score(y_ext_aligned, y_prob_ext),
    "Sensitivity_SLE": tp_old / (tp_old + fn_old),
    "Specificity_Healthy": tn_old / (tn_old + fp_old),
    "False_Positive": fp_old,
    "False_Negative": fn_old,
    "True_Healthy": tn_old,
    "True_SLE": tp_old
}

cm_old_df = pd.DataFrame(
    cm_old,
    index=["True_Healthy", "True_SLE"],
    columns=["Pred_Healthy", "Pred_SLE"]
)

print(cm_old_df)

y_pred_new = (y_prob_ext >= new_threshold).astype(int)

cm_new = confusion_matrix(y_ext_aligned, y_pred_new)
tn_new, fp_new, fn_new, tp_new = cm_new.ravel()

new_results = {
    "Model": "New Threshold",
    "Threshold": new_threshold,
    "Accuracy": accuracy_score(y_ext_aligned, y_pred_new),
    "ROC_AUC": roc_auc_score(y_ext_aligned, y_prob_ext),
    "Sensitivity_SLE": tp_new / (tp_new + fn_new),
    "Specificity_Healthy": tn_new / (tn_new + fp_new),
    "False_Positive": fp_new,
    "False_Negative": fn_new,
    "True_Healthy": tn_new,
    "True_SLE": tp_new
}

cm_new_df = pd.DataFrame(
    cm_new,
    index=["True_Healthy", "True_SLE"],
    columns=["Pred_Healthy", "Pred_SLE"]
)

print(cm_new_df)

results_summary_df = pd.DataFrame([old_results, new_results])

results_summary_df

import pandas as pd
import os

base_path = "/content/drive/MyDrive/SLE_Project"
os.makedirs(base_path, exist_ok=True)

excel_path = base_path + "/external_validation_threshold_comparison.xlsx"

with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
    results_summary_df.to_excel(writer, sheet_name="Summary", index=False)
    cm_old_df.to_excel(writer, sheet_name="Old_Threshold_CM")
    cm_new_df.to_excel(writer, sheet_name="New_Threshold_CM")

print("Excel file saved successfully at:")
print(excel_path)

import pandas as pd

excel_path = "/content/drive/MyDrive/SLE_Project/external_validation_threshold_comparison.xlsx"

pd.read_excel(excel_path, sheet_name=None).keys()

pred_df = pd.DataFrame({
    "Sample": y_ext_aligned.index,
    "True_Label": y_ext_aligned.values,
    "Prob_SLE": y_prob_ext,
    "Pred_0_5": (y_prob_ext >= 0.5).astype(int),
    "Pred_0_3": (y_prob_ext >= 0.3).astype(int),
}).set_index("Sample")

with pd.ExcelWriter(excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    pred_df.to_excel(writer, sheet_name="Per_Sample_Preds")

print("Added Per_Sample_Preds sheet.")

from google.colab import files

files.download("/content/drive/MyDrive/SLE_Project/external_validation_threshold_comparison.xlsx")

from sklearn.calibration import calibration_curve
from sklearn.metrics import brier_score_loss
import matplotlib.pyplot as plt
import os
import joblib

# External probabilities from final 8-gene model
# If y_prob_ext already exists from external validation, this line is optional
X_ext_scaled = scaler.transform(X_ext_final)
y_prob_ext = model.predict_proba(X_ext_scaled)[:, 1]

# Brier score
brier_ext = brier_score_loss(y_ext_aligned, y_prob_ext)

print("External Calibration Brier Score:", brier_ext)

# Calibration curve
prob_true_ext, prob_pred_ext = calibration_curve(
    y_ext_aligned,
    y_prob_ext,
    n_bins=5,
    strategy="quantile"
)

# Plot
plt.figure(figsize=(6,6))

plt.plot(
    prob_pred_ext,
    prob_true_ext,
    marker="o",
    linewidth=2,
    label="External 8-Gene Model"
)

plt.plot(
    [0, 1],
    [0, 1],
    "--",
    linewidth=2,
    label="Perfect Calibration"
)

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title(f"External Calibration Curve\nBrier Score = {brier_ext:.4f}")

plt.legend()
plt.grid(alpha=0.3)

# Save figure
save_path = "/content/drive/MyDrive/SLE_Project/MANUSCRIPT_FIGURES"
os.makedirs(save_path, exist_ok=True)

plt.savefig(
    f"{save_path}/Figure_External_Calibration_8Gene_Model.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.calibration import CalibratedClassifierCV

# Refit calibrated model using training data
cal_model = CalibratedClassifierCV(
    clean_model,
    method='sigmoid',
    cv=5
)

cal_model.fit(
    X_train_clean_scaled,
    y_train
)

# External prediction
y_prob_ext_cal = cal_model.predict_proba(
    X_ext_scaled
)[:,1]

from sklearn.metrics import brier_score_loss

brier_cal = brier_score_loss(
    y_ext_aligned,
    y_prob_ext_cal
)

print("Calibrated External Brier:", brier_cal)

from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

# Use calibrated probabilities
prob_true_cal, prob_pred_cal = calibration_curve(
    y_ext_aligned,
    y_prob_ext_cal,
    n_bins=5,
    strategy='quantile'
)

plt.figure(figsize=(6,6))

plt.plot(
    prob_pred_cal,
    prob_true_cal,
    marker='o',
    linewidth=2,
    label='Calibrated External 8-Gene Model'
)

plt.plot(
    [0,1],
    [0,1],
    '--',
    linewidth=2,
    label='Perfect Calibration'
)

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")

plt.title(
    "External Calibration Curve\n"
    "Brier Score = {:.4f}".format(brier_cal)
)

plt.legend()
plt.grid(alpha=0.3)

plt.savefig(
    f"{save_path}/Figure_External_Calibration_Calibrated8Gene.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

[x for x in globals().keys() if 'ext' in x.lower()]

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# External validation ROC
fpr_ext, tpr_ext, _ = roc_curve(y_ext, y_prob_ext)
auc_ext = auc(fpr_ext, tpr_ext)

plt.figure(figsize=(6,5))

plt.plot(
    fpr_ext,
    tpr_ext,
    linewidth=2,
    label=f'External Validation (AUC = {auc_ext:.3f})'
)

plt.plot([0,1], [0,1], '--', linewidth=1)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('External Validation ROC Curve (GSE61635)')
plt.legend(loc='lower right')

plt.tight_layout()
plt.show()

print(f"External Validation AUC = {auc_ext:.4f}")

!pip install GEOparse -q

from google.colab import drive

drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive')

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if "GSE88884" in file:
            print(os.path.join(root, file))

import os
print(os.listdir("/content/drive/MyDrive/SLE_GEO_Project"))

import os
print(os.listdir("/content/drive/MyDrive/SLE_Project"))

import pandas as pd

save_path = "/content/drive/MyDrive/SLE_GEO_Project"

X = pd.read_pickle(f"{save_path}/GSE88884_filtered.pkl")

y = pd.read_csv(
    f"{save_path}/GSE88884_sledai.csv",
    index_col=0
).squeeze("columns")

print("X:", X.shape)
print("y:", y.shape)
print("Aligned:", (X.index == y.index).all())

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

# Compute Spearman correlation for all probes (vectorized)
corrs = []
pvals = []

for col in X.columns:
    r, p = spearmanr(X[col], y)
    corrs.append(r)
    pvals.append(p)

severity_df = pd.DataFrame({
    "Probe": X.columns,
    "Spearman_r": corrs,
    "P_value": pvals
})

severity_df = severity_df.sort_values("P_value")
severity_df.head(20)

from statsmodels.stats.multitest import multipletests

severity_df["FDR"] = multipletests(
    severity_df["P_value"],
    method="fdr_bh"
)[1]

severity_df = severity_df.sort_values("FDR")

severity_df.head(20)

severity_probes = severity_df[
    (severity_df["FDR"] < 0.05) &
    (severity_df["Spearman_r"].abs() >= 0.20)
].copy()

print("Significant severity probes:", severity_probes.shape)
severity_probes.head(20)

save_path = "/content/drive/MyDrive/SLE_GEO_Project"

severity_df.to_csv(f"{save_path}/GSE88884_severity_all_probes.csv", index=False)
severity_probes.to_csv(f"{save_path}/GSE88884_severity_significant_probes.csv", index=False)

print(X.columns[:20])

import GEOparse

gse = GEOparse.get_GEO(
    geo="GSE88884",
    destdir="/content/drive/MyDrive/SLE_GEO_Project"
)

platform_id = list(gse.gpls.keys())[0]
annot = gse.gpls[platform_id].table

print(annot.columns.tolist())

print(gse.gpls["GPL17586"].table.columns.tolist())

annot = gse.gpls["GPL17586"].table.copy()

mapping = annot[["probeset_id", "gene_assignment"]].copy()
mapping.columns = ["Probe", "gene_assignment"]

mapping.head()

import numpy as np
import pandas as pd

def extract_gene_symbol(x):
    if pd.isna(x):
        return np.nan

    parts = [p.strip() for p in str(x).split("//")]

    if len(parts) >= 2:
        return parts[1].upper()

    return np.nan

mapping["Gene"] = mapping["gene_assignment"].apply(extract_gene_symbol)

mapping = mapping.dropna(subset=["Gene"])

mapping.head()

severity_genes = severity_probes.merge(
    mapping[["Probe", "Gene"]],
    on="Probe",
    how="left"
)

severity_genes = severity_genes.dropna(subset=["Gene"])

print("Mapped severity probes:", severity_genes.shape)
severity_genes.head(20)

severity_probes_fixed = severity_probes.copy()

severity_probes_fixed["Probe_base"] = (
    severity_probes_fixed["Probe"]
    .astype(str)
    .str.split(":")
    .str[0]
)

mapping_fixed = mapping.copy()
mapping_fixed["Probe_base"] = mapping_fixed["Probe"].astype(str)

severity_genes = severity_probes_fixed.merge(
    mapping_fixed[["Probe_base", "Gene"]],
    on="Probe_base",
    how="left"
)

severity_genes = severity_genes.dropna(subset=["Gene"])

print("Mapped severity probes:", severity_genes.shape)
severity_genes.head(20)

severity_gene_summary = (
    severity_genes
    .sort_values("FDR")
    .groupby("Gene", as_index=False)
    .agg({
        "Probe": "first",
        "Spearman_r": "first",
        "P_value": "first",
        "FDR": "first"
    })
    .sort_values("FDR")
)

print("Unique severity genes:", severity_gene_summary.shape)
severity_gene_summary.head(20)

save_path = "/content/drive/MyDrive/SLE_GEO_Project"

severity_gene_summary.to_csv(
    f"{save_path}/GSE88884_severity_genes_mapped.csv",
    index=False
)

print("Saved 209 severity genes.")

final_genes = ['IFI27', 'ZBP1', 'SCRN1', 'ABCB1', 'CDCA7', 'GADD45A', 'TFDP1', 'KLHDC8B']

final_genes = [g.upper() for g in final_genes]

overlap_genes = sorted(
    set(final_genes) & set(severity_gene_summary["Gene"].str.upper())
)

print("Overlap genes:", overlap_genes)

overlap_details = severity_gene_summary[
    severity_gene_summary["Gene"].isin(['IFI27','ZBP1','CDCA7'])
].copy()

overlap_details

overlap_details.to_csv(
    f"{save_path}/FINAL_overlap_3_genes.csv",
    index=False
)

# Top 100 severity-associated genes
top100_genes = severity_gene_summary.head(100)["Gene"].str.upper().tolist()

print("Top 100 genes:", len(top100_genes))
print(top100_genes[:10])

top100_info = severity_gene_summary.head(100).copy()

top100_probes = top100_info["Probe"].tolist()

X_top100 = X[top100_probes].copy()

# Rename probe columns to gene names
X_top100.columns = top100_info["Gene"].values

print(X_top100.shape)
X_top100.head()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(
    X_top100, y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ridge = Ridge(alpha=1.0)

ridge.fit(X_train_scaled, y_train)

y_pred_ridge = ridge.predict(X_test_scaled)

print("Ridge MAE:", mean_absolute_error(y_test, y_pred_ridge))
print("Ridge RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_ridge)))
print("Ridge R2:", r2_score(y_test, y_pred_ridge))

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

rf_reg = RandomForestRegressor(
    n_estimators=300,
    max_depth=8,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf_reg.fit(X_train, y_train)

y_pred_rf = rf_reg.predict(X_test)

print("RF MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RF RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("RF R2:", r2_score(y_test, y_pred_rf))

from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

xgb_reg = XGBRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_reg.fit(X_train, y_train)

y_pred_xgb = xgb_reg.predict(X_test)

print("XGB MAE:", mean_absolute_error(y_test, y_pred_xgb))
print("XGB RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))
print("XGB R2:", r2_score(y_test, y_pred_xgb))

top20_info = severity_gene_summary.head(20).copy()

top20_probes = top20_info["Probe"].tolist()

X_top20 = X[top20_probes].copy()

# Rename columns → gene names
X_top20.columns = top20_info["Gene"].values

print(X_top20.shape)
X_top20.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_top20, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ridge = Ridge(alpha=1.0)
ridge.fit(X_train_scaled, y_train)

y_pred_ridge = ridge.predict(X_test_scaled)

print("Ridge MAE:", mean_absolute_error(y_test, y_pred_ridge))
print("Ridge RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_ridge)))
print("Ridge R2:", r2_score(y_test, y_pred_ridge))

len(y_pred_ridge)
len(y_test)

plt.figure(figsize=(6,5))

plt.scatter(y_test, y_pred_ridge, alpha=0.6)

plt.plot(
    [min(y_test), max(y_test)],
    [min(y_test), max(y_test)],
    'r--'
)

plt.xlabel("Observed SLEDAI")
plt.ylabel("Predicted SLEDAI")
plt.title("Ridge Regression Prediction")

plt.tight_layout()
plt.show()

plt.text(
    0.05, 0.95,
    f"MAE = 2.72\nRMSE = 3.62\nR² = 0.091",
    transform=plt.gca().transAxes,
    verticalalignment='top',
    bbox=dict(facecolor='white', alpha=0.8)
)

import seaborn as sns

sns.regplot(
    x=y_test,
    y=y_pred_ridge,
    scatter=False,
    color='blue'
)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.figure(figsize=(6,6))

# Scatter
plt.scatter(y_test, y_pred_ridge, alpha=0.6)

# Regression trend line
sns.regplot(
    x=y_test,
    y=y_pred_ridge,
    scatter=False,
    color='blue'
)

# Perfect agreement line
min_val = min(min(y_test), min(y_pred_ridge))
max_val = max(max(y_test), max(y_pred_ridge))

plt.plot(
    [min_val, max_val],
    [min_val, max_val],
    'r--',
    label='Perfect prediction'
)

# Metrics
plt.text(
    0.05, 0.95,
    "MAE = 2.72\nRMSE = 3.62\nR² = 0.091",
    transform=plt.gca().transAxes,
    verticalalignment='top',
    bbox=dict(facecolor='white', alpha=0.8)
)

plt.xlabel("Observed SLEDAI")
plt.ylabel("Predicted SLEDAI")
plt.title("Ridge Regression Prediction")
plt.legend()

plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=6,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("RF MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RF RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("RF R2:", r2_score(y_test, y_pred_rf))

from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("XGB MAE:", mean_absolute_error(y_test, y_pred_xgb))
print("XGB RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))
print("XGB R2:", r2_score(y_test, y_pred_xgb))

import numpy as np
import pandas as pd

y_class = (y > 10).astype(int)

print(y_class.value_counts())
print(y_class.value_counts(normalize=True))

top20_info = severity_gene_summary.head(20).copy()

top20_probes = top20_info["Probe"].tolist()

X_top20 = X[top20_probes].copy()
X_top20.columns = top20_info["Gene"].values

print(X_top20.shape)
X_top20.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_top20,
    y_class,
    test_size=0.2,
    random_state=42,
    stratify=y_class
)

print(y_train.value_counts())
print(y_test.value_counts())

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

log_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        random_state=42
    ))
])

log_clf.fit(X_train, y_train)

y_pred_log = log_clf.predict(X_test)
y_prob_log = log_clf.predict_proba(X_test)[:, 1]

print("Logistic Accuracy:", accuracy_score(y_test, y_pred_log))
print("Logistic AUC:", roc_auc_score(y_test, y_prob_log))
print(confusion_matrix(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_clf.fit(X_train, y_train)

y_pred_rf = rf_clf.predict(X_test)
y_prob_rf = rf_clf.predict_proba(X_test)[:, 1]

print("RF Accuracy:", accuracy_score(y_test, y_pred_rf))
print("RF AUC:", roc_auc_score(y_test, y_prob_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

from xgboost import XGBClassifier

xgb_clf = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_clf.fit(X_train, y_train)

y_pred_xgb = xgb_clf.predict(X_test)
y_prob_xgb = xgb_clf.predict_proba(X_test)[:, 1]

print("XGB Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("XGB AUC:", roc_auc_score(y_test, y_prob_xgb))
print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

import pandas as pd
import matplotlib.pyplot as plt

regression_results = pd.DataFrame({
    "Model": ["Ridge", "Random Forest", "XGBoost"],
    "MAE": [2.724, 2.755, 2.866],
    "RMSE": [3.620, 3.652, 3.796],
    "R2": [0.091, 0.075, 0.001]
})

fig, axes = plt.subplots(1,3, figsize=(12,4))

axes[0].bar(regression_results["Model"], regression_results["MAE"])
axes[0].set_title("MAE")

axes[1].bar(regression_results["Model"], regression_results["RMSE"])
axes[1].set_title("RMSE")

axes[2].bar(regression_results["Model"], regression_results["R2"])
axes[2].set_title("R²")

plt.tight_layout()
plt.show()

[x for x in globals() if 'prob' in x.lower()]

[x for x in globals() if 'severity' in x.lower()]

[x for x in globals() if 'label' in x.lower()]

[x for x in globals() if 'bin' in x.lower()]

[x for x in globals() if 'class' in x.lower()]

[x for x in globals() if 'y_' in x.lower()]

len(y_test)
len(y_prob_log)
len(y_pred_log)
len(y_class)

for var in globals():
    try:
        if len(globals()[var]) == 352:
            print(var)
    except:
        pass

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Logistic Regression
fpr_log, tpr_log, _ = roc_curve(y_test, y_prob_log)
auc_log = auc(fpr_log, tpr_log)

# Random Forest
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)
auc_rf = auc(fpr_rf, tpr_rf)

# XGBoost
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, y_prob_xgb)
auc_xgb = auc(fpr_xgb, tpr_xgb)

plt.figure(figsize=(7,6))

plt.plot(fpr_log, tpr_log, linewidth=2,
         label=f'Logistic Regression (AUC = {auc_log:.3f})')

plt.plot(fpr_rf, tpr_rf, linewidth=2,
         label=f'Random Forest (AUC = {auc_rf:.3f})')

plt.plot(fpr_xgb, tpr_xgb, linewidth=2,
         label=f'XGBoost (AUC = {auc_xgb:.3f})')

plt.plot([0,1], [0,1], 'k--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves for Severity Classification')
plt.legend(loc='lower right')

plt.tight_layout()
plt.show()

len(y_pred_ridge)
len(y_test)

plt.figure(figsize=(6,5))

plt.scatter(y_test, y_pred_ridge, alpha=0.6)

plt.plot(
    [min(y_test), max(y_test)],
    [min(y_test), max(y_test)],
    'r--'
)

plt.xlabel("Observed SLEDAI")
plt.ylabel("Predicted SLEDAI")
plt.title("Ridge Regression Prediction")

plt.tight_layout()
plt.show()

print(y_test[:10])

[x for x in globals() if 'sledai' in x.lower()]

[x for x in globals() if 'ridge' in x.lower()]

severity_df.head()

print(severity_df.columns)

[col for col in severity_df.columns if 'sle' in col.lower()]

[x for x in globals() if 'gse' in x.lower()]

[x for x in globals() if 'meta' in x.lower()]

[x for x in globals() if 'pheno' in x.lower()]

[x for x in globals() if 'clinical' in x.lower()]

[x for x in globals() if 'sledai' in x.lower()]

overlap_genes = ['IFI27', 'ZBP1', 'CDCA7']

overlap_details = severity_gene_summary[
    severity_gene_summary["Gene"].str.upper().isin(overlap_genes)
].copy()

overlap_details

overlap_details.to_csv(
    f"{save_path}/FINAL_overlap_3_genes.csv",
    index=False
)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.bar(overlap_details["Gene"], overlap_details["Spearman_r"])
plt.axhline(0, linestyle="--")
plt.xlabel("Overlap Genes")
plt.ylabel("Spearman correlation with SLEDAI")
plt.title("Overlap Genes Associated with SLE Severity")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

overlap_details["minus_log10_FDR"] = -np.log10(overlap_details["FDR"])

plt.figure(figsize=(6,4))
plt.bar(overlap_details["Gene"], overlap_details["minus_log10_FDR"])
plt.xlabel("Overlap Genes")
plt.ylabel("-log10(FDR)")
plt.title("Statistical Significance of Overlap Genes")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

for gene in overlap_genes:
    probe = overlap_details.loc[
        overlap_details["Gene"].str.upper() == gene, "Probe"
    ].values[0]

    plt.figure(figsize=(5,4))
    sns.regplot(
        x=X[probe],
        y=y,
        scatter_kws={"alpha":0.4},
        line_kws={"color":"red"}
    )
    plt.xlabel(f"{gene} expression")
    plt.ylabel("SLEDAI")
    plt.title(f"{gene} expression vs SLEDAI")
    plt.show()

y_class = (y > 10).astype(int)

for gene in overlap_genes:
    probe = overlap_details.loc[
        overlap_details["Gene"].str.upper() == gene, "Probe"
    ].values[0]

    plot_df = pd.DataFrame({
        "Expression": X[probe],
        "Severity": y_class.map({0: "Low/Moderate", 1: "High"})
    })

    plt.figure(figsize=(5,4))
    sns.boxplot(data=plot_df, x="Severity", y="Expression")
    sns.stripplot(data=plot_df, x="Severity", y="Expression", alpha=0.25)
    plt.title(f"{gene} expression in Low vs High Severity")
    plt.show()

from sklearn.preprocessing import StandardScaler
import seaborn as sns

overlap_probes = overlap_details["Probe"].tolist()

X_overlap = X[overlap_probes].copy()
X_overlap.columns = overlap_details["Gene"].values

X_overlap_scaled = pd.DataFrame(
    StandardScaler().fit_transform(X_overlap),
    index=X_overlap.index,
    columns=X_overlap.columns
)

plot_df = X_overlap_scaled.copy()
plot_df["SLEDAI"] = y

plot_df = plot_df.sort_values("SLEDAI")

plt.figure(figsize=(6,8))
sns.heatmap(
    plot_df[overlap_details["Gene"].values],
    cmap="vlag",
    yticklabels=False
)
plt.title("Heatmap of Overlap Genes Ordered by SLEDAI")
plt.xlabel("Genes")
plt.ylabel("Samples ordered by SLEDAI")
plt.show()

!pip install matplotlib-venn -q

from matplotlib_venn import venn2
import matplotlib.pyplot as plt

diagnostic_genes = set(['IFI27', 'ZBP1', 'SCRN1', 'ABCB1', 'CDCA7', 'GADD45A', 'TFDP1', 'KLHDC8B'])
severity_genes_set = set(severity_gene_summary["Gene"].str.upper())

plt.figure(figsize=(5,5))
venn2(
    [diagnostic_genes, severity_genes_set],
    set_labels=("Diagnostic genes", "Severity genes")
)
plt.title("Overlap Between Diagnostic and Severity Genes")
plt.show()

plt.figure(figsize=(6,4))
plt.bar(overlap_details["Gene"], overlap_details["Spearman_r"])
plt.axhline(0, linestyle="--")
plt.xlabel("Overlap Genes")
plt.ylabel("Spearman correlation with SLEDAI")
plt.title("Overlap Genes Associated with SLE Severity")

plt.savefig(f"{save_path}/overlap_genes_correlation_plot.png", dpi=300, bbox_inches="tight")
plt.show()

import joblib

save_path = "/content/drive/MyDrive/SLE_GEO_Project"

joblib.dump(log_clf, f"{save_path}/severity_logistic_model.pkl")

print("Model saved successfully")

joblib.dump(X_top20.columns.tolist(), f"{save_path}/severity_top20_genes.pkl")

print("Feature list saved")

def severity_alt(x):
    if x <= 8:
        return 0   # low
    elif x <= 15:
        return 1   # moderate
    else:
        return 2   # high

y_multi = y.apply(severity_alt)

print(y_multi.value_counts())
print(y_multi.value_counts(normalize=True))

X_train, X_test, y_train, y_test = train_test_split(
    X_top20,
    y_multi,   # 👈 NOT y_class
    test_size=0.2,
    stratify=y_multi,
    random_state=42
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

multi_log = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        multi_class="multinomial",
        max_iter=5000,
        class_weight="balanced",
        random_state=42
    ))
])

multi_log.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = multi_log.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

top100_info = severity_gene_summary.head(100).copy()

top100_probes = top100_info["Probe"].tolist()

X_top100 = X[top100_probes].copy()

# rename to gene names
X_top100.columns = top100_info["Gene"].values

# fix duplicate genes (VERY IMPORTANT)
X_top100 = X_top100.groupby(X_top100.columns, axis=1).mean()

print(X_top100.shape)
X_top100.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_top100,
    y_class,
    test_size=0.2,
    stratify=y_class,
    random_state=42
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

log_100 = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        random_state=42
    ))
])

log_100.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

y_pred = log_100.predict(X_test)
y_prob = log_100.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

overlap_genes = ["IFI27", "ZBP1", "CDCA7"]

overlap_details = severity_gene_summary[
    severity_gene_summary["Gene"].str.upper().isin(overlap_genes)
].copy()

overlap_probes = overlap_details["Probe"].tolist()

X_overlap = X[overlap_probes].copy()
X_overlap.columns = overlap_details["Gene"].values

corr_matrix = X_overlap.corr(method="spearman")
corr_matrix

from sklearn.preprocessing import StandardScaler
import pandas as pd

X_overlap_scaled = pd.DataFrame(
    StandardScaler().fit_transform(X_overlap),
    index=X_overlap.index,
    columns=X_overlap.columns
)

module_score = X_overlap_scaled.mean(axis=1)

print("Module score vs SLEDAI:")
print(module_score.corr(y, method="spearman"))

import seaborn as sns
import matplotlib.pyplot as plt

plot_df = pd.DataFrame({
    "Module_score": module_score,
    "SLEDAI": y
})

plt.figure(figsize=(5,4))
sns.regplot(
    data=plot_df,
    x="Module_score",
    y="SLEDAI",
    scatter_kws={"alpha":0.35}
)
plt.title("IFI27-ZBP1-CDCA7 module vs SLEDAI")
plt.show()

# Top 20 genes
top20_info.to_csv(f"{save_path}/top20_severity_genes.csv", index=False)

# Overlap genes
overlap_details.to_csv(f"{save_path}/overlap_genes.csv", index=False)

# Correlation matrix
corr_matrix.to_csv(f"{save_path}/coexpression_matrix.csv")

# Module score
plot_df.to_csv(f"{save_path}/module_score_vs_sledai.csv", index=False)

import pandas as pd

save_path = "/content/drive/MyDrive/SLE_GEO_Project"

excel_file = f"{save_path}/GSE88884_Severity_Analysis_Results.xlsx"

with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:

    severity_df.to_excel(
        writer,
        sheet_name="All_Probe_Correlations",
        index=False
    )

    severity_probes.to_excel(
        writer,
        sheet_name="Significant_Probes",
        index=False
    )

    severity_gene_summary.to_excel(
        writer,
        sheet_name="Mapped_Severity_Genes",
        index=False
    )

    overlap_details.to_excel(
        writer,
        sheet_name="Overlap_3_Genes",
        index=False
    )

    corr_matrix.to_excel(
        writer,
        sheet_name="Coexpression_Matrix"
    )

    plot_df.to_excel(
        writer,
        sheet_name="Module_Score_SLEDAI",
        index=False
    )

print("Excel file saved successfully:")
print(excel_file)

plt.savefig("/content/drive/MyDrive/SLE_GEO_Project/MANUSCRIPT_FIGURES/Figure_2_Model_ROC_Comparison.tiff",
            dpi=600, bbox_inches="tight", format="tiff")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Confusion matrix
cm = np.array([[30, 0],
               [20, 79]])

# Class labels
labels = ["Healthy", "SLE"]

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=labels, yticklabels=labels)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")

# Save high-quality figure
plt.savefig("confusion_matrix.png", dpi=300, bbox_inches='tight')

plt.show()

# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Install required package
!pip install gseapy openpyxl -q

# 3. Import libraries
import pandas as pd
import gseapy as gp
import matplotlib.pyplot as plt
import os
import pickle

# 4. Define folder paths

severity_folder = "/content/drive/MyDrive/SLE_GEO_Project"
diagnostic_folder = "/content/drive/MyDrive/SLE_Project"

kegg_output_folder = "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results"
os.makedirs(kegg_output_folder, exist_ok=True)

# 5. Load overlap genes
overlap_path = os.path.join(severity_folder, "overlap_genes.csv")

overlap_df = pd.read_csv(overlap_path)
print(overlap_df.head())
print(overlap_df.columns)

# 6. Extract overlap gene list safely

if overlap_df.shape[1] == 1:
    overlap_genes = overlap_df.iloc[:, 0].dropna().astype(str).tolist()
else:
    # change column name here if needed
    overlap_genes = overlap_df.iloc[:, 0].dropna().astype(str).tolist()

overlap_genes = list(set(overlap_genes))

print("Overlap genes:")
print(overlap_genes)
print("Number of overlap genes:", len(overlap_genes))

organism="human"

kegg_overlap = gp.enrichr(
    gene_list=overlap_genes,
    gene_sets="KEGG_2021_Human",
    organism="human",
    outdir=os.path.join(kegg_output_folder, "Overlap_Genes_KEGG"),
    cutoff=1.0
)

overlap_kegg_results = kegg_overlap.results
overlap_kegg_results.head(20)

overlap_kegg_results.to_excel(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/overlap_genes_KEGG_results.xlsx",
    index=False
)

overlap_kegg_table = overlap_kegg_results[
    ["Term", "Overlap", "Adjusted P-value", "Odds Ratio", "Combined Score", "Genes"]
]

overlap_kegg_table.to_excel(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/overlap_genes_KEGG_clean_table.xlsx",
    index=False
)

overlap_kegg_table

import pickle
import os

# Load SHAP diagnostic genes

final_genes_path = "/content/drive/MyDrive/SLE_Project/final_clean_8_genes.pkl"

with open(final_genes_path, "rb") as f:
    shap_genes = pickle.load(f)

print(shap_genes)
print("Number of SHAP genes:", len(shap_genes))

kegg_shap = gp.enrichr(
    gene_list=shap_genes,
    gene_sets="KEGG_2021_Human",
    organism="human",
    outdir=os.path.join(kegg_output_folder, "SHAP_Diagnostic_Genes_KEGG"),
    cutoff=1.0
)

shap_kegg_results = kegg_shap.results
shap_kegg_results.head(20)

import numpy as np

# Load top 20 severity genes
top20_path = "/content/drive/MyDrive/SLE_GEO_Project/top20_severity_genes.csv"

top20_df = pd.read_csv(top20_path)
print(top20_df.head())
print(top20_df.columns)

# Extract severity gene list
top20_genes = top20_df.iloc[:, 0].dropna().astype(str).tolist()
top20_genes = list(set(top20_genes))

print(top20_genes)
print("Number of severity genes:", len(top20_genes))

# KEGG enrichment for severity genes
kegg_severity = gp.enrichr(
    gene_list=top20_genes,
    gene_sets="KEGG_2021_Human",
    organism="human",
    outdir=os.path.join(kegg_output_folder, "Top20_Severity_Genes_KEGG"),
    cutoff=1.0
)

severity_kegg_results = kegg_severity.results
severity_kegg_results.head(20)

severity_kegg_results.to_excel(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/top20_severity_genes_KEGG_results.xlsx",
    index=False
)

sig_severity = severity_kegg_results[
    severity_kegg_results["Adjusted P-value"] < 0.05
].copy()

sig_severity[["Term", "Overlap", "Adjusted P-value", "Genes"]]

import matplotlib.pyplot as plt
import numpy as np

sig_severity["Gene Count"] = sig_severity["Overlap"].apply(
    lambda x: int(x.split("/")[0])
)

sig_severity["-log10(FDR)"] = -np.log10(
    sig_severity["Adjusted P-value"]
)

plt.figure(figsize=(9,6))

scatter = plt.scatter(
    sig_severity["-log10(FDR)"],
    sig_severity["Term"],
    s=sig_severity["Gene Count"] * 250
)

plt.xlabel("-log10 Adjusted P-value")
plt.ylabel("KEGG Pathway")
plt.title("KEGG Enrichment Analysis of Severity-Associated Genes")

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/Severity_KEGG_Dotplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

globals().keys()

organism="human"

# Final SHAP genes
shap_genes = [
    "IFI27",
    "ZBP1",
    "SCRN1",
    "ABCB1",
    "CDCA7",
    "GADD45A",
    "TFDP1",
    "KLHDC8B"
]

# KEGG enrichment
kegg_shap = gp.enrichr(
    gene_list=shap_genes,
    gene_sets="KEGG_2021_Human",
    organism="human",
    outdir=None
)

# Save results
shap_kegg_results = kegg_shap.results

# Significant pathways
sig_shap = shap_kegg_results[
    shap_kegg_results["Adjusted P-value"] < 0.05
].copy()

sig_shap = sig_shap[
    ["Term", "Overlap", "Adjusted P-value", "Genes"]
]

sig_shap

# Significant SHAP KEGG pathways

sig_shap = shap_kegg_results[
    shap_kegg_results["Adjusted P-value"] < 0.05
].copy()

sig_shap = sig_shap[
    ["Term", "Overlap", "Adjusted P-value", "Genes"]
]

sig_shap

sig_shap.to_excel(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/Final_Significant_SHAP_KEGG.xlsx",
    index=False
)

sig_shap["Gene Count"] = sig_shap["Overlap"].apply(
    lambda x: int(x.split("/")[0])
)

sig_shap["-log10(FDR)"] = -np.log10(
    sig_shap["Adjusted P-value"]
)

plt.figure(figsize=(9,6))

plt.scatter(
    sig_shap["-log10(FDR)"],
    sig_shap["Term"],
    s=sig_shap["Gene Count"] * 250
)

plt.xlabel("-log10 Adjusted P-value")
plt.ylabel("KEGG Pathway")
plt.title("KEGG Enrichment Analysis of SHAP Diagnostic Genes")

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/SHAP_KEGG_Dotplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

sig_overlap = overlap_kegg_results[
    overlap_kegg_results["Adjusted P-value"] < 0.05
].copy()

sig_overlap = sig_overlap[
    ["Term", "Overlap", "Adjusted P-value", "Genes"]
]

sig_overlap

sig_overlap.to_excel(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/Final_Significant_Overlap_KEGG.xlsx",
    index=False
)

sig_overlap["Gene Count"] = sig_overlap["Overlap"].apply(
    lambda x: int(x.split("/")[0])
)

sig_overlap["-log10(FDR)"] = -np.log10(
    sig_overlap["Adjusted P-value"]
)

plt.figure(figsize=(8,5))

plt.scatter(
    sig_overlap["-log10(FDR)"],
    sig_overlap["Term"],
    s=sig_overlap["Gene Count"] * 350
)

plt.xlabel("-log10 Adjusted P-value")
plt.ylabel("KEGG Pathway")
plt.title("KEGG Enrichment Analysis of Overlapping Biomarkers")

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/Overlap_KEGG_Dotplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(9,6))

plt.barh(
    sig_severity["Term"],
    sig_severity["-log10(FDR)"]
)

plt.xlabel("-log10 Adjusted P-value")
plt.ylabel("KEGG Pathway")
plt.title("KEGG Enrichment of Severity-Associated Genes")

plt.gca().invert_yaxis()

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/Severity_KEGG_Barplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(9,6))

plt.barh(
    sig_shap["Term"],
    sig_shap["-log10(FDR)"]
)

plt.xlabel("-log10 Adjusted P-value")
plt.ylabel("KEGG Pathway")
plt.title("KEGG Enrichment of SHAP Diagnostic Genes")

plt.gca().invert_yaxis()

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/SHAP_KEGG_Barplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(9,6))

plt.barh(
    sig_overlap["Term"],
    sig_overlap["-log10(FDR)"]
)

plt.xlabel("-log10 Adjusted P-value")
plt.ylabel("KEGG Pathway")
plt.title("KEGG Enrichment of Overlapping Biomarkers")

plt.gca().invert_yaxis()

plt.tight_layout()

plt.savefig(
    "/content/drive/MyDrive/SLE_GEO_Project/KEGG_Analysis_Results/Overlap_KEGG_Barplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# ============================================
# 2. IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler

# ============================================
# 3. DEFINE SAVE FOLDER
# ============================================

results_folder = "/content/drive/MyDrive/SLE_GEO_Project/BIOLOGICAL_INTERPRETATION_FIGURES"

os.makedirs(results_folder, exist_ok=True)

print("Results folder created.")

# ============================================
# 4. LOAD TOP 20 SEVERITY GENES
# ============================================

top20_path = "/content/drive/MyDrive/SLE_GEO_Project/top20_severity_genes.csv"

top20_df = pd.read_csv(top20_path)

print(top20_df.head())
print(top20_df.columns)

# Extract gene list

top20_genes = top20_df.iloc[:, 0].dropna().astype(str).tolist()

top20_genes = list(set(top20_genes))

print(top20_genes)
print("Number of genes:", len(top20_genes))

# ============================================
# 5. LOAD CLEANED SEVERITY DATA
# ============================================

severity_data_path = "/content/drive/MyDrive/SLE_GEO_Project/GSE88884_filtered.pkl"

severity_df = pd.read_pickle(severity_data_path)

print(severity_df.shape)
severity_df.head()

# ============================================
# 6. CHECK COLUMNS
# ============================================

print(severity_df.columns.tolist())

print(severity_df.columns.tolist())

print(type(severity_df))

print(severity_df.shape)
print(severity_df.columns[:20])
print(severity_df.index[:10])

[col for col in severity_df.columns if "sled" in str(col).lower()]

# ==============================
# 3. SET PATHS
# ==============================
base_path = "/content/drive/MyDrive/SLE_GEO_Project"

fig_path = os.path.join(base_path, "SEVERITY_BIOMARKER_INTERPRETATION_FIGURES")
os.makedirs(fig_path, exist_ok=True)

print("Figures will be saved in:", fig_path)

# ==============================
# 4. LOAD TOP 20 SEVERITY GENES
# ==============================
top20_path = os.path.join(base_path, "top20_severity_genes.csv")

top20_df = pd.read_csv(top20_path)
print(top20_df.head())
print(top20_df.columns)

# Extract gene list
top20_genes = top20_df.iloc[:, 0].dropna().astype(str).tolist()
top20_genes = list(dict.fromkeys(top20_genes))

print("Top 20 genes:")
print(top20_genes)
print("Number of genes:", len(top20_genes))

# Commented out IPython magic to ensure Python compatibility.
# %who

available_genes = [g for g in top20_genes if g in severity_df.columns]
print(available_genes)
print(len(available_genes))

import os

for file in os.listdir("/content/drive/MyDrive/SLE_GEO_Project"):
    if "gene" in file.lower() or "mapped" in file.lower() or "severity" in file.lower() or "sledai" in file.lower():
        print(file)

# ============================================
# LOAD GENE-LEVEL SEVERITY DATA
# ============================================

gene_expr_path = "/content/drive/MyDrive/SLE_GEO_Project/GSE88884_severity_genes_mapped.csv"

expr_df = pd.read_csv(gene_expr_path, index_col=0)

print(expr_df.shape)
expr_df.head()

available_genes = [g for g in top20_genes if g in expr_df.columns]

print(available_genes)
print("Number available:", len(available_genes))

print(expr_df.shape)
print(expr_df.head())
print(expr_df.index[:10])
print(expr_df.columns[:10])

severity_corr_df = expr_df.reset_index()

severity_corr_df.head()

import numpy as np
import matplotlib.pyplot as plt
import os

fig_path = "/content/drive/MyDrive/SLE_GEO_Project/SEVERITY_BIOMARKER_INTERPRETATION_FIGURES"

volcano_df = severity_corr_df.copy()
volcano_df["-log10(p-value)"] = -np.log10(volcano_df["P_value"])

volcano_df["Significant"] = (
    (volcano_df["FDR"] < 0.05) &
    (abs(volcano_df["Spearman_r"]) > 0.2)
)

plt.figure(figsize=(9,7))

plt.scatter(
    volcano_df["Spearman_r"],
    volcano_df["-log10(p-value)"],
    alpha=0.5
)

sig_df = volcano_df[volcano_df["Significant"]]

plt.scatter(
    sig_df["Spearman_r"],
    sig_df["-log10(p-value)"],
    alpha=0.9
)

plt.axhline(-np.log10(0.05), linestyle="--")
plt.axvline(0.2, linestyle="--")
plt.axvline(-0.2, linestyle="--")

plt.xlabel("Spearman Correlation with SLEDAI")
plt.ylabel("-log10 P-value")
plt.title("Volcano Plot of Severity-Associated Genes")

plt.tight_layout()

plt.savefig(
    os.path.join(fig_path, "Severity_Genes_Volcano_Plot.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()

top20_volcano = volcano_df[
    volcano_df["Gene"].isin(top20_genes)
].copy()

plt.figure(figsize=(10,8))

plt.scatter(
    volcano_df["Spearman_r"],
    volcano_df["-log10(p-value)"],
    alpha=0.35
)

plt.scatter(
    top20_volcano["Spearman_r"],
    top20_volcano["-log10(p-value)"],
    alpha=0.95
)

for _, row in top20_volcano.iterrows():
    plt.text(
        row["Spearman_r"],
        row["-log10(p-value)"],
        row["Gene"],
        fontsize=8
    )

plt.axhline(-np.log10(0.05), linestyle="--")
plt.axvline(0.2, linestyle="--")
plt.axvline(-0.2, linestyle="--")

plt.xlabel("Spearman Correlation with SLEDAI")
plt.ylabel("-log10 P-value")
plt.title("Volcano Plot Highlighting Top 20 Severity Genes")

plt.tight_layout()

plt.savefig(
    os.path.join(fig_path, "Top20_Severity_Genes_Labeled_Volcano.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()

top20_corr = severity_corr_df[
    severity_corr_df["Gene"].isin(top20_genes)
].copy()

top20_corr = top20_corr.sort_values("Spearman_r")

plt.figure(figsize=(10,8))

plt.barh(
    top20_corr["Gene"],
    top20_corr["Spearman_r"]
)

plt.xlabel("Spearman Correlation with SLEDAI")
plt.ylabel("Gene")
plt.title("Top 20 Severity-Associated Genes Correlated with SLEDAI")

plt.tight_layout()

plt.savefig(
    os.path.join(fig_path, "Top20_Severity_Correlation_Barplot.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()